### ISSUE TITLE
[Bug] Huge difference result in Earthquake on Population Analysis

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2235]
# Problem
Different result (very big difference) between general result and detailed result

# Detail
I run InaSAFE analysis EQ (raster) padang with population (raster) padang. The analysis went well but the result is really different. I got a lot of people that affected in detailed gender report. And also the minimum needs result different number between general and detailed (both people and minimum needs)

# Screenshot
 In this example, EQ in Padang produce 235.000 person displaced:
![image](https://cloud.githubusercontent.com/assets/2520159/9484660/6dd7b792-4bd9-11e5-9e4c-be1c4ca447fb.png)

When you look at detailed gender, you will notice that it change very big, from 235.000 person to 697.688.810 person (really huge isn't it?)
![image](https://cloud.githubusercontent.com/assets/2520159/9484708/eb53c170-4bd9-11e5-814e-e4e73abe5519.png)

 
# Platform
QGIS 2.8.3 with InaSAFE 3.2 Windows 7 64bit

# Data used
EQ Padang 2009
Padang population

# How to produce this error
Run InaSAFE analysis for those both data or EQ data with people

**Comment by adissadis** [comment]
This problem also happen in Flood Raster with Building. I think detailed report produced more bigger result than the general report, which i think its really strange.

**Comment by cchristelis** [comment]
Hi @adissadis,

The population count issue is fixed in PR 2256. Since this issue and the buildings issue seem quite unrelated, I'm going to pull the buildings comments into a new issue.

**Comment by cchristelis** [comment]
The new buildings issue is #2258

**Comment by adissadis** [comment]
hi @cchristelis the problem still occur here. We tested again with padang earthquake from http://data.inasafe.org/InaSAFE%203.1%20Training%20Data/ and still produce a huge difference between population general and detailed.

This problem also happen with aggregation data. like this screenshoot below:
![image](https://cloud.githubusercontent.com/assets/2520159/9539201/ab31a076-4d78-11e5-8173-f20910a7be8e.png)

**Comment by Charlotte-Morgan** [comment]
@samnawi - can you please see if you found this same bug in your testing? If you did, please label this issue as a release blocker.

**Comment by samnawi** [comment]
OK @Charlotte-Morgan .
Yeah, I Also find this problem in my computer.

This is the result :
**EQ Raster & Population**
![selection_143](https://cloud.githubusercontent.com/assets/8871958/9540464/520fb18e-4d89-11e5-9c49-f381f8d2aae1.png)
![selection_144](https://cloud.githubusercontent.com/assets/8871958/9540471/5b367ebe-4d89-11e5-8417-908539178724.png)

I Think the data that use to run this IF is same with @adissadis 
Platform :
Linux Ubuntu 14.04 64-Bit
QGIS 2.8.3
InaSAFE 3.2.0.dev-29b9ca4

**Comment by cchristelis** [comment]
Hi @Charlotte-Morgan, @adissadis and @samnawi,

The issue was closed before the PR https://github.com/AIFDR/inasafe/pull/2256 was applied. You should have more joy after pulling now.

**Comment by samnawi** [comment]
Ok @cchristelis I just pull again, and now the result is fine.

Thank you

**Comment by harrymahar** [comment]
Hi @cchristelis , This week HOT ID team doing test for InaSAFE 3.2.5 dev-master

Today, I run Earthquake IF in Jogjakarta and Padang. I using scenario for population in both area. Unfortunately, this bug/issue appears again. So these are my screenshoot problem :
![eq_3](https://cloud.githubusercontent.com/assets/2534179/11973808/cc630a18-a990-11e5-924f-319639fe3f53.PNG)

![eq_bug1](https://cloud.githubusercontent.com/assets/2534179/11973809/d590aac8-a990-11e5-8df2-69ec410b149b.PNG)

My Platform :
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.4 Wien
InaSAFE 3.2.5 dev-master

Data :
Hazard : Earthquake_Mentawai_WGS84 and Earthquake_Yogyakarta_2006_WGS84

Exposure : Sumatra_Population_WGS84 and Java_Population_WGS84

**Comment by samnawi** [comment]
@harrymahar I also get this problem again.
I think the problem has appeared again. 
In the previous version, the result is fine.
But, I've been tried again in a couple of minutes ago, and the result is wrong again.
There is a huge difference result in earthquake on Population Analysis

![selection_013](https://cloud.githubusercontent.com/assets/8871958/12110095/36f21de0-b3bb-11e5-9b65-3feb21ece447.png)

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux 
I think this need to be fixed urgently - I've just added the release blocker etc labels as it been around for a while.

**Comment by ismailsunni** [comment]
Update:

After looking at the file's history, see: https://github.com/inasafe/inasafe/commits/develop/safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py

@cchristelis has fixed it on 25 August 2015, with his commit 0e064c2b1c8f06f4ba389d01dbe6ddbd6f32f336

But, on 9 September 2015, there is this strange huge commit: https://github.com/inasafe/inasafe/commit/90c718b5f06dd9041056ecdc58c93d71211af099, and it's like altering so many file (200+ files).

Then boom, the problem comes back.

I need to check how to revert the problem, since it's quite complicated.
