### ISSUE TITLE
BUG : Type Error Problem When running InaSAFE

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2846]
### Problem
After I, @felix-yew and @ivanbusthomi doing a systematic testing for InaSAFE 3.4, we found some IF that cannot run. One of the issues is Type Error. Maybe this issue is similar with https://github.com/inasafe/inasafe/issues/2816, but we will try to explore all of IF that has similar error (type error).

We got the error in :
**1.Tsunami Raster VS Roads**
Similar with https://github.com/inasafe/inasafe/issues/2816

**2.Tsunami Vector VS Population Vector** --> Aggregation only
![image](https://cloud.githubusercontent.com/assets/8871958/15536664/86e2c7be-229c-11e6-924c-4dcc893d4954.png)

**3.EQ Vector VS landcover** --> Aggregation Only
![image](https://cloud.githubusercontent.com/assets/8871958/15536320/0ca7be92-229b-11e6-8a32-d6dd385a14cc.png)

**4.Volcano Vector VS Landcover** --> Aggregation only
![image](https://cloud.githubusercontent.com/assets/8871958/15536447/6e7aac9c-229b-11e6-90e9-83dcf7ad69f1.png)

**5.Generic Hazard Vector VS Pop Vector**
![image](https://cloud.githubusercontent.com/assets/8871958/15536592/30ea3f2c-229c-11e6-83ce-1afdbd3963ad.png)

### Environment
* InaSAFE : 3.4
* QGIS : 2.8.8 and 2.14.2
* OS : Win 7 64 Bit

Data : https://www.dropbox.com/sh/tlk9slv6mjzdtfr/AAAgluvO9bBQoobO4Ai-ssSJa?dl=0

### Proposed Solution
Make it happy

cc : @timlinux @Charlotte-Morgan @ismailsunni @felix-yew @ivanbusthomi 

Thank You

**Comment by Charlotte-Morgan** [comment]
@ismailsunni @timlinux
I think this looks like a release blocker for anything that ran previously




On 25 May 2016, at 5:26 PM, Adi Kurniawan <notifications@github.com<mailto:notifications@github.com>> wrote:

Problem

After I, @felix-yew<https://github.com/felix-yew> and @ivanbusthomi<https://github.com/ivanbusthomi> doing a systematic testing for InaSAFE 3.4, we found some IF that cannot run. One of the issues is Type Error. Maybe this issue is similar with #2816<https://github.com/inasafe/inasafe/issues/2816>, but we will try to explore all of IF that has similar error (type error).

We got the error in :
1.Tsunami Raster VS Roads
Similar with #2816<https://github.com/inasafe/inasafe/issues/2816>

2.Tsunami Vector VS Population Vector --> Aggregation only
[image]<https://cloud.githubusercontent.com/assets/8871958/15536664/86e2c7be-229c-11e6-924c-4dcc893d4954.png>

3.EQ Vector VS landcover --> Aggregation Only
[image]<https://cloud.githubusercontent.com/assets/8871958/15536320/0ca7be92-229b-11e6-8a32-d6dd385a14cc.png>

4.Volcano Vector VS Landcover --> Aggregation only
[image]<https://cloud.githubusercontent.com/assets/8871958/15536447/6e7aac9c-229b-11e6-90e9-83dcf7ad69f1.png>

5.Generic Hazard Vector VS Pop Vector
[image]<https://cloud.githubusercontent.com/assets/8871958/15536592/30ea3f2c-229c-11e6-83ce-1afdbd3963ad.png>

Environment

  *   InaSAFE : 3.4
  *   QGIS : 2.8.8 and 2.14.2
  *   OS : Win 7 64 Bit

Data : https://www.dropbox.com/sh/tlk9slv6mjzdtfr/AAAgluvO9bBQoobO4Ai-ssSJa?dl=0

Proposed Solution

Make it happy

cc : @timlinux<https://github.com/timlinux> @Charlotte-Morgan<https://github.com/Charlotte-Morgan> @ismailsunni<https://github.com/ismailsunni> @felix-yew<https://github.com/felix-yew> @ivanbusthomi<https://github.com/ivanbusthomi>

Thank You

-

**Comment by ivanbusthomi** [comment]
### Work around
**environment** :
OS Windows 7
QGIS 2.14.1
InaSAFE 3.4

I've tried modifying the aggregation data by converting the multipart to singlepart, using _Multipart to Singlepart_ menu. **It worked** for me, without any error. This is what I got using _semeru continuous raster_ hazard on _raster population_ exposure :
![1](https://cloud.githubusercontent.com/assets/7351977/15563320/b5543d40-2331-11e6-9797-8cb6ad632b87.PNG)

### Problem
The consequence of using this singlepart data is there are a lot of zero rows and duplicates that occur, like this one below
![2](https://cloud.githubusercontent.com/assets/7351977/15563337/f2a51822-2331-11e6-8411-621f7f787a85.PNG)
 
It might be related to issues #2318 , because when i retried the case using singlepart data, i got no _No Data_ values in the report.

**The Problems** are:
* In real life there are always a multipart/multipolygon data, especially districts or subdistricts that have island in their region.
* Not all of the user understand the concept of multipart and singlepart geometries, and i'm afraid it would be too much for them converting their data from multipart to singlepart

### Suggestion
Maybe add a functionality in the code to automatically convert the aggregation data that contains multipart to singlepart, and remove the duplicated rows that occur in the result?

**Comment by ismailsunni** [comment]
I am able to replicate the issues in OSX and QGIS 2.8.3. Except the first one.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - thanks for confirming teh multipart problem. I think it is a known issue and just as we have to support users to prepare their data prior to analysis, maybe we add this to the list. @adissadis can you please look to see if this limitation is covered in training for new users.

@ismailsunni  - for now maybe we can add a limitation to the dock and or a nice happy warning message

@easmetz  - something to know about for training materials :)

**Comment by timlinux** [comment]
I think the only viable option is to support multipart features for aggregation. Historically we did not support it because the NUMPY based geometry algorithms written by Ole do not support multipart features. On our road map we will be deprecating his safe_layer which will allow us to work with QGIS native data layers including multipart features.

For now I think we should move this to 3.5 and remove the blocker status as it is not something we can address in the next day or two. As a short term work around, it might be good to:

* add this to the limitations text something like: "Multipart features will be converted to single part features during analysis."
* @ismailsunni Add better error handling for type errors

Another possible temporary work around would be to append a sequential number to each exploded multi polygon part so that in @ivanbusthomi 's example would list out as ``KAB. BLITAR1``, ``KAB. BLITAR2`` and so on...

**Comment by ivanbusthomi** [comment]
@timlinux @Charlotte-Morgan @ismailsunni 
After trying the other problem mentioned by @samnawi above, apparently the singlepart aggregation layer only fix/removes the error in problem 6. the errors are still persist in the other problem (problem 1 through 5), below are the detailed results.
![2 8 8](https://cloud.githubusercontent.com/assets/7351977/15569238/4a543c38-235a-11e6-86d5-e930b30bc02f.PNG)

I will try another work around if possible, and update the result here.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi 
This is weird, the only consistent thing is QGIS 2.8.8 - do these run in 2.14?

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan 
As updated by mas @felix-yew in the first post, the error also run in 2.14.1
![ref](https://cloud.githubusercontent.com/assets/13621886/15564434/8e53d600-233c-11e6-9637-2bd7e82f0fc3.png)

Here are my detailed report that contains the result test for these problems from 2.14.1
![3](https://cloud.githubusercontent.com/assets/7351977/15569497/5835e8d2-235b-11e6-9c72-2011d813ed6e.PNG)

**Comment by ismailsunni** [comment]
Hi, here my result by using QGIS 2.8.3 on OSX. Seems a little bit different:

<img width="1167" alt="screen shot 2016-05-26 at 21 19 38" src="https://cloud.githubusercontent.com/assets/1421861/15577667/a9740702-2387-11e6-8969-9886c64eea30.png">

The orange one (attribute error) is fixed in #2854, but I haven't tested it again, since I have not much idea about the fix (is it ok or not ok).

Now, I wonder, why this is QGIS version specific and OS specific.

**Comment by ismailsunni** [comment]
From my error table:
I have some fixes in #2857 for TypeError NoneType (red blood error) and Attribute Error (pale orange error). But I am not sure still.

For the `TypeError, QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'` error, I check in the classified polygon people, the SymDifference between two polygon returns None. I check the polygon with QGIS, and they shouldn't return None. I have script to generate the polygon: https://github.com/ismailsunni/scripts/blob/master/qgis_polygon.py

I took polygon 1 and polygon 2 from the data that give None in SymDifference. The first polygon is a normal polygon. Second one is a multipart polygon with some holes. Third polygon is modified second polygon, still with some holes but not multipart.

As we can see after running the script, polygon 2 or polygon 3 give None when applied SymDifference to polygon 1. Although, from viewing it, they are overlap.

From the definition here : http://docs.qgis.org/2.2/en/docs/user_manual/plugins/plugins_ftools.html#geoprocessing-tools

```
Overlay layers such that output contains those areas of the input and difference layers that do not intersect.
```

Not sure if I understand correctly, but SymDiff for me is like XOR in math logic. So, the SymDiff looks like doesn't give proper result from me.
<img width="1291" alt="screen shot 2016-05-27 at 11 05 57" src="https://cloud.githubusercontent.com/assets/1421861/15597520/0b7b1044-23fb-11e6-82fb-2da7a99ad45f.png">

**Comment by felix-yew** [comment]
Hi mas @ismailsunni, I just add a little information test your PR, here my result by using QGIS 2.8.8. on Windows 7 64-bit. Some hazard can work properly.

![image](https://cloud.githubusercontent.com/assets/13621886/15607209/52496d50-243b-11e6-8165-d4315a5fd84c.png)

I think the most of the PR is already running well. In case of tsunami (raster) and road (vector) still error in my Windows.

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - what is the status of this now - i think this is fixed in PR #2881?

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan, I have test again and here the result :

![image](https://cloud.githubusercontent.com/assets/13621886/15668524/f0b689a2-2745-11e6-9302-1a09ba0727ec.png)
The Tsunami vs Roads still having error, I try in whole Ambon area. And very took a long time processing. In small area, it still processing :disappointed: 

Cc: @ismailsunni

**Comment by felix-yew** [comment]
Hi @ismailsunni I try with small area analysis and still get Exception error.

![image](https://cloud.githubusercontent.com/assets/13621886/15672487/1b2d067e-275b-11e6-934b-e87863302a14.png)

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - can you please see if this is still an issue or fixed

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan and mas @ismailsunni 

About this issue, tsunami (raster) vs roads (vector), I think it has fixed in InaSAFE 3.4.1. The processing data can be work properly and faster performance :clap:
![image](https://cloud.githubusercontent.com/assets/13621886/16066235/caadb752-32db-11e6-911e-727ea4251ccb.png)

I think it is already fixed yet :clap: :+1:
