### ISSUE TITLE
Duplicate code between the dock and the wizard

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3001]
### Problem
Thanks to @NyakudyaA, I noticed that when an analysis is finished using IFCW, the behaviour is not the same than when we are using the dock.
In the IFCW, I found that a lot of code has been copied from the dock. However, for example I brought some fix on the dock these last weeks, but I wasn't aware about that duplication in the wizard.

### Proposed solution
We should avoid duplication in the code between the dock and the analysis_handler

Quick thoughts about some inheritance ? 
        inasafe_gui
        /        \
dock      wizard

Of course, the dock will still have a lot of code, it's just to avoid duplication with the analysis_handler.

**Comment by timlinux** [comment]
Hmm that would be interesting...I don't know if it makes sense to inherit everything from dock. What about a shared base class that is used by both? That would also help to make dock smaller....

**Comment by ismailsunni** [comment]
Hi @timlinux and @Gustry 
I have another suggestion for this issue:
In the wizard, we use AnalysisHandler class to run the impact function. It only needs to :
1. Create the analysis handler
2. Setup and run the Impact Function
3. Set action for print and report composer button.

I think, we can do it also in Dock. So, Dock, will not call the Impact Function directly, but it will do the same  as the Wizard. This means, AnalysisHandler is an interface to run Impact Function.]By doing this, we will have these benefits:

1. No more code duplication, since all code to set up and run IF will be in the AnalysisHandler
2. Dock will have less code, since we move out the IF setup and run.
3. Better concern separation. Dock and Wizard will only manage the UI things (choose layer, click button, show result from the AnalysisHandler, etc)
4. We can add more user interface in the future more easily. 

The cons so far:
1. We need to send signal from the AnalysisHandler to the Wizard or the Dock so that they will aware the state of the analysis. But it's already done in the Wizard - AnalysisHandler.

Any comment for this idea?

**Comment by timlinux** [comment]
@ismailsunni sorry if its a bomb question - but why do we need analysis handler at all? Cant IF just handle all the activities of model execution + print production? I think it will be much cleaner and easier to explain / train people with...

**Comment by ismailsunni** [comment]
No worries, I like to discuss to prevent future problem :D 

- model execution, yes the IF can do it. The AnalysisHandler will help to get the parameter to setup from dock and wizard. It's not a big benefit of using AnalysisHandler.
- print production. Currently, still no. I saw in the current state, the dock still handle it. Now, I remember that we want to put the print production in the Impact Function. This is a note for @lucernae 

One thing that is still missing from the Impact Function is handling the Exception or failure in the analysis. Currently, the Dock and the Wizard's AnalysisHandler are handling the exception and creating the error message. If we want to make it not duplicate, we need to move the exception handling and error message creation to the IF. Is that ok to do it in the IF?

**Comment by timlinux** [comment]
> Currently, the Dock and the Wizard's AnalysisHandler are handling the exception and creating the error message. If we want to make it not duplicate, we need to move the exception handling and error message creation to the IF. Is that ok to do it in the IF?

Big +1 fro me. At the end of the IF run the dock / wizard could just ask the IF for its message and it can say whatever went right / wrong.

And yeah making pdf print happing in IF is a task for @lucernae 

Thanks @ismailsunni

**Comment by Gustry** [comment]
So all the reporting should go in the IF ? (generate the report and print it to pdf)

Big +1 to manage exceptions in the IF it self. It's too much work for a client class now. We have many client : dock, wizard, command line, geosafe ...
The IF should have 3 states at the end : 
* everything was fine, we display the report
* something went wrong from the user (invalid keywords, no features impacted, not enough memory). We should display a nice error message to help the user to fix that.
* something went wrong programmatically (from the developer side). The user should raise the issue.

Where do we manage the layer display (layer group) ?

**Comment by lucernae** [comment]
For the printing part in the IF, yes we absolutely can do it.
Right now reporting logic is nicely separated (I already refactor some reporting logic in the dock). To move it to IF will be to just instantiate ImpactReport inside IF. Then have dock transferred user choices like chosen template or report location or needs profile, when the report is generated.
So, what can I think of about pdf printing in IF would be to create another function wrapper in the IF (it is actually just passing it to ImpactReport).

Also for this:

> One thing that is still missing from the Impact Function is handling the Exception or failure in the analysis. Currently, the Dock and the Wizard's AnalysisHandler are handling the exception and creating the error message. If we want to make it not duplicate, we need to move the exception handling and error message creation to the IF. Is that ok to do it in the IF?

I would like to propose that we have other class to store the logic of displaying the error (Qt related code) in separate class, let's say this a handler class. Since I think IF need to be modular, if we use IF for command line like InaSAFE Headless or GeoSAFE, it would be troublesome if IF is still connected with dock. What I think is have another module  or python file to list all possible exception class of IF (so new developer would be able to see what possible error can be raised by IF). Then the workflow in dock would be for dock to run IF and pass the displaying error business to this handler class. Then for what @Gustry said:

> -  everything was fine, we display the report

Have handler class display it. Pass report output in html format to handler class (or whatever format that the handler needs).

> - something went wrong from the user (invalid keywords, no features impacted, not enough memory). We should display a nice error message to help the user to fix that.

Catch selected exceptions from IF analysis or reporting and pass it to handler class to display.

> - something went wrong programmatically (from the developer side). The user should raise the issue.

Have this exceptions that we didn't expect, to be displayed by handler class in a nicely trackable format, so the user can (for example) submit it to github. Like what we did previously by displaying stack trace etc.

The nice thing that could happen if we have a separate handler class is:
- IF doesn't need to be cluttered with presentation logic like formatting the error or logic to display the errror to the dock. IF shouldn't care about this. Since IF will also be used by Headless or command line.
- Model execution is in IF
- Print/reporting logic is in IF via delegation to ImpactReport class
- Presentation logic (displaying error message of IF to dock or wizard) should be in separate handler class.
- We can put the exception message text or template in definitions, separated from dock or IF, so it can be edited (and translated) by @Charlotte-Morgan or the minions.
- Handler class can work by matching IF exceptions (or report exceptions) with the exception messages definitions and format them as needed.
- Handler class can be subclassed so it deals the presentation logic. For example Dock Handler and Wizard Handler might use the same error message, but both showing to a different target. Or, it might be subclassed because the error message is in different output. For example, Dock Handler (or in @ismailsunni 's term, Analysis Handler) will output an HTML formatted error message to Qt element. Then we can create (or subclass) another one for InaSAFE Headless who will display it on friendly text message in command prompt. The nice thing is, they both got the text from definitions.
- We could reuse reporting logic like jinja2 templating if we want. Or just use the old messaging.

Cons:
- We need to refactor dock and wizard and put presentation codes in separate class (in @ismailsunni 's term, the Analysis Handler class).

**Comment by ismailsunni** [comment]
Hi @lucernae 

Actually, I was thinking the IF will send signal that the interface (dock, wizard, headless, etc) can receive it. It will have all the message. Then the interface will need to connect the signal receiver to the correct method. For example, show to in the dock for Dock, stdout in the command line, depends on the interface.

By doing this, we don't need extra class.


Basically, I put @lucernae 's Handler class into the Dock, Wizard, etc to make the code simpler.

cc @Gustry @timlinux

**Comment by Gustry** [comment]
Can we close this ticket @ismailsunni @myarjunar?

**Comment by ismailsunni** [comment]
Hmm, do we still want the handler class?

**Comment by Gustry** [comment]
No, but the original problem has been solved I think now

**Comment by ismailsunni** [comment]
I just check a little bit in the `dock.py` and `step_fc90_analysis.py`, they do still have some (almost) duplicated code (in `accept` method for `dock.py`, and `setup_and_run_analysis` in `step_fc90_analysis.py`
https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/dock.py#L1132
https://github.com/inasafe/inasafe/blob/develop/safe/gui/tools/wizard/step_fc90_analysis.py#L121

Or is it normal? 

/me is trying to remember which one is the duplicated one
