### ISSUE TITLE
BUG Python Error

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3615]
# problem
I get the following python error when running pop raster and flood vector analysis with no aggregation layer

results are produced in dock but the system is still spinning ...

# error message
```
An error has occurred while executing Python code: 

KeyError: '-1' 
Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 793, in accept
    generate_impact_report(self.impact_function, self.iface)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 55, in generate_impact_report
    impact_report.process_component()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 599, in process_component
    context = _extractor_method(self, component)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\report\extractors\infographics.py", line 178, in population_infographic_extractor
    analysis_layer)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\report\extractors\util.py", line 121, in value_from_field_name
    return analysis_layer.getFeatures().next()[field_index]
KeyError: '-1'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/AIFDR_ADMIN/.qgis2/python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg
C:\Program Files (x86)\ArcGIS\Desktop10.2\bin
C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy
C:\Program Files (x86)\ArcGIS\Desktop10.2\ArcToolbox
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/AIFDR_ADMIN/.qgis2//python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/AIFDR/AIFDR II - SDA/05 Test Data/InaSAFE 4.0
```

**Comment by lucernae** [comment]
This should have been fixed by now

**Comment by Gustry** [comment]
<img width="871" alt="screen shot 2017-01-20 at 12 11 35" src="https://cloud.githubusercontent.com/assets/1609292/22136823/b5929d58-df09-11e6-807e-4ca1f51583c1.png">

@lucernae I still have this error. I have updated from develop just now : 
* Aggregation : grid jakarta 4326
* Hazard : flood multipart
* Exposure : population 20 * 20

@Charlotte-Morgan and I used an exposure raster continuous.

**Comment by Gustry** [comment]
We should catch every exceptions and stop the busy cursor in any case.

**Comment by Gustry** [comment]
I think this has been fixed by @lucernae We don't have this error.
